// @generated by hand for leverx-schema

diesel::table! {
    leverx_events (event_digest) {
        event_digest -> Text,
        event_type -> Text,
        module -> Text,
        package_id -> Text,
        transaction_digest -> Text,
        checkpoint -> Int8,
        timestamp_ms -> Int8,
        parsed_json -> Jsonb,
    }
}

diesel::table! {
    markets (market_key) {
        market_key -> Text,
        oracle_id -> Text,
        expiry_ms -> Int8,
        strike -> Int8,
        higher_strike -> Int8,
        is_up -> Bool,
        is_range -> Bool,
        first_seen_at_ms -> Int8,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    predict_managers (manager_id) {
        manager_id -> Text,
        owner -> Nullable<Text>,
        account_id -> Nullable<Text>,
        created_at_ms -> Int8,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    user_proxies (account_id) {
        account_id -> Text,
        owner -> Text,
        predict_manager_id -> Nullable<Text>,
        borrowed_quote -> Int8,
        created_at_ms -> Int8,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    limit_mint_orders (placed_event_digest) {
        placed_event_digest -> Text,
        position_key -> Text,
        account_id -> Text,
        owner -> Text,
        oracle_id -> Text,
        expiry_ms -> Int8,
        strike -> Int8,
        higher_strike -> Int8,
        is_range -> Bool,
        is_up -> Bool,
        collateral_asset -> Text,
        limit_premium_per_unit -> Int8,
        slippage_bps -> Int8,
        market_ask_at_place -> Nullable<Int8>,
        margin_quote -> Int8,
        leverage_bps -> Int8,
        quantity -> Int8,
        order_expires_ms -> Int8,
        status -> Text,
        placed_at_ms -> Int8,
        placed_by -> Nullable<Text>,
        executed_event_digest -> Nullable<Text>,
        filled_at_ms -> Nullable<Int8>,
        market_ask_at_fill -> Nullable<Int8>,
        mint_cost -> Nullable<Int8>,
        executor -> Nullable<Text>,
        cancelled_event_digest -> Nullable<Text>,
        cancelled_at_ms -> Nullable<Int8>,
        cancelled_by -> Nullable<Text>,
    }
}

diesel::table! {
    leveraged_positions (position_key, account_id) {
        position_key -> Text,
        account_id -> Text,
        owner -> Text,
        predict_manager_id -> Nullable<Text>,
        oracle_id -> Text,
        expiry_ms -> Int8,
        strike -> Int8,
        higher_strike -> Int8,
        is_up -> Bool,
        is_range -> Bool,
        collateral_asset -> Text,
        open_quantity -> Int8,
        margin_quote -> Int8,
        borrow_quote -> Int8,
        leverage_bps -> Int8,
        mint_cost -> Int8,
        last_order_type -> Nullable<Int2>,
        status -> Text,
        opened_at_ms -> Nullable<Int8>,
        closed_at_ms -> Nullable<Int8>,
        realized_payout -> Int8,
    }
}

diesel::table! {
    market_trades (event_digest) {
        event_digest -> Text,
        position_key -> Text,
        oracle_id -> Text,
        trade_kind -> Text,
        side -> Text,
        quantity -> Int8,
        premium_per_unit -> Nullable<Int8>,
        notional_quote -> Nullable<Int8>,
        account_id -> Nullable<Text>,
        owner -> Nullable<Text>,
        order_type -> Nullable<Int2>,
        timestamp_ms -> Int8,
    }
}

diesel::table! {
    vault_snapshots (event_digest) {
        event_digest -> Text,
        vault_id -> Text,
        event_type -> Text,
        timestamp_ms -> Int8,
        nav -> Nullable<Int8>,
        utilization_bps -> Nullable<Int8>,
        total_borrowed -> Nullable<Int8>,
        borrow_rate_bps -> Nullable<Int8>,
        lp_apr_bps -> Nullable<Int8>,
        amount -> Nullable<Int8>,
        account_id -> Nullable<Text>,
        owner -> Nullable<Text>,
        payload -> Jsonb,
    }
}

diesel::table! {
    collateral_assets (coin_type) {
        coin_type -> Text,
        registry_id -> Text,
        decimals -> Int2,
        max_ltv_bps -> Int8,
        liquidation_ltv_bps -> Int8,
        max_conf_bps -> Int8,
        updated_at_ms -> Int8,
        event_digest -> Text,
    }
}

diesel::table! {
    swap_pools (collateral_asset) {
        collateral_asset -> Text,
        pool_id -> Text,
        registry_id -> Text,
        updated_at_ms -> Int8,
        event_digest -> Text,
    }
}

diesel::table! {
    protocol_settings (registry_id) {
        registry_id -> Text,
        vault_id -> Nullable<Text>,
        predict_id -> Nullable<Text>,
        fee_collector_id -> Nullable<Text>,
        trading_paused -> Bool,
        pyth_max_age_secs -> Nullable<Int8>,
        base_rate_bps -> Nullable<Int8>,
        kink_utilization_bps -> Nullable<Int8>,
        slope1_bps -> Nullable<Int8>,
        slope2_bps -> Nullable<Int8>,
        flash_fee_bps -> Nullable<Int8>,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    collateral_balances (position_key, account_id, collateral_asset) {
        position_key -> Text,
        account_id -> Text,
        collateral_asset -> Text,
        balance_atoms -> Int8,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    position_triggers (account_id, oracle_id, is_range) {
        account_id -> Text,
        oracle_id -> Text,
        is_range -> Bool,
        take_profit_premium -> Int8,
        stop_loss_premium -> Int8,
        active -> Bool,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    proxy_executors (account_id, executor) {
        account_id -> Text,
        executor -> Text,
        active -> Bool,
        registered_at_ms -> Int8,
        revoked_at_ms -> Nullable<Int8>,
    }
}

diesel::table! {
    liquidations (event_digest) {
        event_digest -> Text,
        position_key -> Text,
        account_id -> Text,
        owner -> Text,
        keeper -> Text,
        collateral_asset -> Text,
        debt_repaid -> Int8,
        collateral_seized -> Int8,
        quote_from_swap -> Int8,
        surplus_quote -> Int8,
        health_bps -> Int8,
        had_position_redeem -> Bool,
        timestamp_ms -> Int8,
    }
}

diesel::table! {
    account_timeline (event_digest) {
        event_digest -> Text,
        account_id -> Text,
        owner -> Nullable<Text>,
        event_type -> Text,
        timestamp_ms -> Int8,
        payload -> Jsonb,
    }
}

diesel::table! {
    user_points (owner) {
        owner -> Text,
        account_id -> Nullable<Text>,
        volume_quote -> Int8,
        trade_count -> Int8,
        points -> Int8,
        first_trade_at_ms -> Nullable<Int8>,
        last_trade_at_ms -> Nullable<Int8>,
        updated_at_ms -> Int8,
    }
}

diesel::table! {
    global_market_trades (event_digest) {
        event_digest -> Text,
        event_type -> Text,
        predict_id -> Text,
        manager_id -> Text,
        market_key -> Text,
        oracle_id -> Text,
        expiry_ms -> Int8,
        strike -> Int8,
        higher_strike -> Int8,
        is_up -> Bool,
        is_range -> Bool,
        quote_asset -> Text,
        trade_side -> Text,
        quantity -> Int8,
        cost -> Nullable<Int8>,
        payout -> Nullable<Int8>,
        ask_price -> Nullable<Int8>,
        bid_price -> Nullable<Int8>,
        trader -> Nullable<Text>,
        owner -> Nullable<Text>,
        executor -> Nullable<Text>,
        is_settled -> Nullable<Bool>,
        timestamp_ms -> Int8,
    }
}
